language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
before_script:
  - echo 'Asia/Shanghai' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
    - "/^\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
notifications:
  email:
    recipients:
      - hi@xuyuanxiang.cn
    on_success: never
    on_failure: always
